version: "3.8"
services:
  postgres:
    container_name: QuintaIpuan
    image: postgres:latest
    environment:
      POSTGRES_DB: pousada-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PG_DATA: /data/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-data: