spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Pousada
  config:
    import: optional:classpath:.env[.properties]
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: on
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_AUTH_SERVER}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER}
  admin-server-url: ${KEYCLOAK_ADMIN_SERVER}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

server:
  port: 8081

sendgrid:
  email: ${SENGRID_EMAIL}
  key: ${SENDGRID_KEY}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}
  region: ${MINIO_REGION}
