spring:
  application:
    name: Pousada
  config:
    import: optional:classpath:.env[.properties]
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: on
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
server:
  port: 8081
sendgrid:
  email: ${SENGRID_EMAIL}
  key: ${SENDGRID_KEY}
imagekit:
  chavePrivada: ${CHAVE_PRIVADA_IMAGEKIT}
  urlUpload: ${UPLOAD_URL_IMAGEKIT}